[package]
name = "test-lambda-fn"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.8.8"
aws-sdk-s3 = "1.108.0"
lambda_http = "0.13.0"

tokio = { version = "1", features = ["macros"] }
